### ISSUE TITLE
Prevent submit if Parser Error in equation

### ISSUE THREAD

**Issue by meramos** [kgram/react-equation#22]
I want to prevent a form from being submitted if there is an error in an equation (such as `operatorLast`, `adjecentOperator`, `expectedCloseParens`). I'd like to know if there's a way to set a boolean variable true/false if there is a parsing error in the equation or a way to set a variable with the specific error.

**Comment by kgram** [comment]
There is now. I just pushed 1.0.0-rc.1 of react-equation and equation-resolver. All parsed models and resolved results are now exposed as a ref on the equation-components. As a convenience, `valid` is included, which is false if anything fails parsing or resolving. Here's an example that just logs the ref out.

https://codesandbox.io/s/react-equation-example-forked-swiueq?file=/src/index.js

I'm gonna upgrade dependencies and maybe polish things a bit up before releasing a full 1.0.0, but see if this solves your problem.

**Comment by meramos** [comment]
Thank you! I just used it and it worked!

**Comment by meramos** [comment]
Thank you! I just used it and it worked!
