### ISSUE TITLE
How to make equation fill full width?

### ISSUE THREAD

**Issue by banool** [kgram/react-equation#28]
Hey all, I'm running into a weird rendering problem with my equation:

<img width="1323" alt="image" src="https://user-images.githubusercontent.com/7816187/211545131-ab82987f-7b28-443b-9368-494f8f4f7fab.png">

As you can see, the equation stacks vertically for some reason instead of expanding horizontally.

My equation:

```tsx
const equation =
  "\
  (active - remainingGrant) * ((100 - commissionRate) / 100) * \
  shareholderShareAmount / originalGrantAmount\
";

<EquationEvaluate
  ref={equationRef}
  decimals={{ type: "fixed", digits: 2 }}
  value={equation}
  variables={eqp}
  errorHandler={defaultErrorHandler}
/>
```

I've tried a variety of things with the `style` param (setting the width, changing the font size). I've confirmed that other components in the container expand to the full width. I have looked at all the example codepens from the README and I can't see what I'm missing.

Any help would be much appreciated.

**Comment by banool** [comment]
For further confirmation, this shows the box that the equation is in:
<img width="1313" alt="image" src="https://user-images.githubusercontent.com/7816187/211547072-6e888970-d8d9-49ad-ba92-4a4b4a41bbfa.png">

**Comment by banool** [comment]
I managed to fix it by applying this CSS class to the parent component of the equations: https://github.com/banool/aptos-vesting-dashboard/commit/52f2195bc97a610a5c144e588c0df2d69459c457#diff-cab9aff5dd0caa1f30f70aeabc73ea03b9ecee07c248c2b518e7cfcf057fca8b.

**Comment by kgram** [comment]
@banool Great that you solved it. It sounds weird though, do you have a global style setting `display: block` on SVGs? As far as I can tell, the default is `display: inline`.

**Comment by banool** [comment]
I'm using Chakra UI, I figure it must have been applying some kind of global style yeah.
