### ISSUE TITLE
Flexibility in Specifying the list of Operators and type of brackets that are valid in equation

### ISSUE THREAD

**Issue by codebreaker-v2-0** [kgram/react-equation#33]
Currently, react-equation provides support for all major arithmetic operators, parentheses, and matrix brackets, making it a versatile tool for rendering mathematical expressions. However, there are use cases where we need to restrict the use of certain operators and specify the type of brackets allowed in an expression.

Proposed Enhancement:

I'd like to propose an enhancement to 'react-equation' that allows users to specify and control the operators and brackets that are valid within an expression. This would provide greater flexibility for customising the behaviour of the equation component to suit specific requirements.

Feature Requirements:

Custom Operators: The ability to define a list of operators that are allowed or disallowed in expressions. For instance, being able to permit addition and subtraction while disallowing multiplication and division.

Custom Brackets: The option to specify which types of brackets (e.g., square brackets, angle brackets) are permitted in expressions and which are not.

Feel free to discuss and provide any additional insights or suggestions related to this enhancement. Your feedback is valuable in improving the usability and functionality of 'react-equation.' Thank you!

**Comment by kgram** [comment]
I'm afraid I don't really understand what those use cases would be. When would you want an equation without multiplication?

I think the best way to solve this would be a filter/map on the AST. This would allow you to show an error whenever a disallowed type was mentioned. See my answer here: https://github.com/kgram/react-equation/issues/31.
